### ISSUE TITLE
traefik errors on cos layer with error: hook failed: "metrics-endpoint-relation-joined"

### ISSUE THREAD

**Issue by kaskavel** [canonical/operator#818]
### Bug Description

Solutions QA team has two runs in which traefik errors on cos layer with error: hook failed: "metrics-endpoint-relation-joined"

The cos layer is built on top of kubernetes-aws. 

From the logs: 

2022-08-21 02:20:42 ERROR juju-log metrics-endpoint:10: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 678, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 1545, in _set_scrape_job_spec
    self._set_unit_ip(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 1576, in _set_unit_ip
    unit_ip = str(self._charm.model.get_binding(relation).network.bind_address)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 679, in network
    self._network = self._network_get(self.name, self._relation_id)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 672, in _network_get
    return Network(self._backend.network_get(name, relation_id))
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 724, in __init__
    self.ingress_addresses.append(ipaddress.ip_address(address))
  File "/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'acb396cf5563d429f9ebc8aa23ae47ed-1516332866.us-east-1.elb.amazonaws.com' does not appear to be an IPv4 or IPv6 address

Failed runs: 

https://solutions.qa.canonical.com/testruns/testRun/0b35ee4c-efcf-4f50-a393-696803b31ac9
https://solutions.qa.canonical.com/testruns/testRun/ef230601-4af3-4d6f-89af-4e578985e666

Logs are found on the bottom on the page, on the artifacts repository. 

### To Reproduce

These errors were found on the  fkb-master-kubernetes-focal-aws SKU of our automated test suite.

### Environment

charmed-kubernetes  1.24
stable channel for cos charms. 

### Relevant log output

```shell
Traceback (most recent call last):
  File "./src/charm.py", line 678, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 1545, in _set_scrape_job_spec
    self._set_unit_ip(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 1576, in _set_unit_ip
    unit_ip = str(self._charm.model.get_binding(relation).network.bind_address)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 679, in network
    self._network = self._network_get(self.name, self._relation_id)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 672, in _network_get
    return Network(self._backend.network_get(name, relation_id))
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 724, in __init__
    self.ingress_addresses.append(ipaddress.ip_address(address))
  File "/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'acb396cf5563d429f9ebc8aa23ae47ed-1516332866.us-east-1.elb.amazonaws.com' does not appear to be an IPv4 or IPv6 address
```

**Comment by marosg42** [comment]
We have passing run on AWS where hostname is returned
```
App           Version  Status  Scale  Charm             Channel  Rev  Address                                                                  Exposed  Message
alertmanager           active      1  alertmanager-k8s  edge      28  10.152.183.28                                                            no       
grafana                active      1  grafana-k8s       edge      40  10.152.183.239                                                           no       
loki                   active      1  loki-k8s          edge      41  10.152.183.16                                                            no       
prometheus    2.33.5   active      1  prometheus-k8s    edge      57  10.152.183.145                                                           no       
traefik                active      1  traefik-k8s       edge      84  ae249ccf0ec834714b17b5d01cb75802-1743979818.us-east-1.elb.amazonaws.com  no       

Unit             Workload  Agent  Address          Ports  Message
alertmanager/0*  active    idle   192.168.21.200          
grafana/0*       active    idle   192.168.21.201          
loki/0*          active    idle   192.168.152.202         
prometheus/0*    active    idle   192.168.152.203         
traefik/0*       active    idle   192.168.21.199      
```

The difference is it used v84 of traefik, we are getting errors with v85

**Comment by simskij** [comment]
@PietroPasotti mind taking a look? It sounds on @marosg42 like this might be a regression in the charm after all

**Comment by PietroPasotti** [comment]
I'll get started on monday, I'm in meetings until EOD today.

**Comment by PietroPasotti** [comment]
It still seems to me that it's on `ops`. I can't explain why it only errors out with v85 but, looking at model.py:

```python
        self.ingress_addresses = []  # type: List[_IPAddress]
        for address in network_info.get('ingress-addresses', []):
            self.ingress_addresses.append(ipaddress.ip_address(address))
```

it seems to me that `ops` is incorrectly assuming that network-get will only ever return ip addresses under `ingress-addresses`, while in fact it can also return more exotic things such as `ae249ccf0ec834714b17b5d01cb75802-1743979818.us-east-1.elb.amazonaws.com`.

I'll add a test in ops to see if that case is handled correctly and if not treat it as an ops bug. 
Could I have repro instructions from @kaskavel?

Also it would be great if you had a chance to ssh into the broken traefik unit and get me the raw output of 'network-get'.

**Comment by PietroPasotti** [comment]
Just found in the logs a telling message:
`unit-traefik-0: 02:20:28 INFO juju.api cannot resolve "aac8d811695854f00b8a58be680436ac-273108020.us-east-1.elb.amazonaws.com": lookup aac8d811695854f00b8a58be680436ac-273108020.us-east-1.elb.amazonaws.com: operation was canceled`

Looks like it's juju failing to convert that address into an IP, probably (so I'm told) not a juju bug so much as a missing feature: proper integration with
https://aws.amazon.com/ru/premiumsupport/knowledge-center/elb-find-load-balancer-IP/

**Comment by PietroPasotti** [comment]
FWIW, I could reproduce the bug in `ops`, so whatever the source of this behaviour is (in juju), there's a mismatch between what juju can send and what `ops` is expecting to receive. Wouldn't hurt to add a pydantic ORM layer between api calls and our model code.

**Comment by PietroPasotti** [comment]
I'm following up with juju folks to find a solution to this, but for now it looks like it's not on our side.

**Comment by PietroPasotti** [comment]
Suggestion from juju folks: as a workaround, could anyone affected by this attempt to change the settings of ELB to force it to use ipv4 addresses only? Not sure it's possible.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-ip-address-type.html

**Comment by rwcarlsen** [comment]
So basically, juju tries to resolve hostnames to an IP and in the past has always succeeded.  Until now :P  For failed resolutions, juju just hands back a hostname.  So ops is just overly strict on what it thinks juju will hand back for those addresses.  But also the other issue with ELB should be addressed.

**Comment by rwcarlsen** [comment]
At least on the ops side, we should probably relax that overzealous check requiring the result to be an ip.

**Comment by simskij** [comment]
So, just to make sure: was this issue introduced in a very recent version of `ops`? Otherwise, I'm sensing a red herring here either around whether it really worked in the prior charm revision or if we're solving the **only** issue.

**Comment by PietroPasotti** [comment]
yeah I'm also smelling a fishy one there. I don't think anything relevant recently changed in ops, but it may well be that something relevant changed recently in juju. So if there's a chance that the 'working' setup with traefik v84 used another juju version than the 'broken' setup with traefik v85, then we might have something. Another possibility is that juju only fails to convert the hostname to IP "sometimes", in which case the fact that v84 was used instead of v85 is an irrelevant coincidence.
I need some more repro instructions before I can isolate the specific cause...

**Comment by kaskavel** [comment]
thank you all for your efforts on this. From what I got, you are able to reproduce it, otherwise we are happy to give you access to an environment demonstrating this or be more specific about the scenario, if that helps better. 
About the workaround, we have no problem trying it out in the short term, unless a fix is underway.

**Comment by rwcarlsen** [comment]
I agree there may be some issues in juju.  However, after chatting with juju folks, it sounds like getting a non-ip from juju needs to be allowed by ops - even if it's not necessarily the actual full fix that's needed to resolve this issue.

**Comment by kaskavel** [comment]
just fyi, juju version in the failed runs & in the passing run is the same: 2.9.33 (traefik version is different, as we already discussed).

**Comment by simskij** [comment]
@kaskavel and @marosg42, do you agree that this issue is resolved? The last time I spoke with you, Marian, it sounded like this was still a thing?

**Comment by rwcarlsen** [comment]
This is at least addressed from the ops side.  Any further changes/fixes will need to occur in either traefik and/or juju.

**Comment by sed-i** [comment]
Probably need to publish a traefik charm (to candidate?) with recent ops. Currently it is pinned to 1.5.0.
https://github.com/canonical/traefik-k8s-operator/blob/b57449ea408b1e4feddbdf66d78a43f30007595f/requirements.txt#L1

**Comment by jeffreychang911** [comment]
It seems Solutions QA still seeing this in multiple test runs recently, logs can be found on https://oil-jenkins.canonical.com/artifacts/0b94bb31-700c-4dbc-903d-69bb0db7e466/generated/generated/cos/juju-crashdump-cos-2023-01-23-12.40.00.tar.gz.

We installed traefik from ch:amd64/focal/traefik-k8s-106 for channel edge, should be 1.5.2.

**Comment by benhoyt** [comment]
Hey @jeffreychang911, I've checked the logs you linked to, and it's that same ValueError expecting an IP address but receiving a hostname. It definitely looks like this was fixed already in https://github.com/canonical/operator/releases/tag/1.5.3 with PR https://github.com/canonical/operator/pull/823. So if your charm is on ops 1.5.2, you'll just need to update the charm to use ops >= 1.5.3. Given that [this charm](https://github.com/canonical/traefik-k8s-operator/blob/main/requirements.txt) doesn't pin ops, if you rebuild the charm and re-upload a new revision to Charmhub, that should pick up this fix.

**Comment by sed-i** [comment]
The traefik charm was pinning `ops == 1.5.2` up until 2hrs ago.
